### ISSUE TITLE
add missing fields to | product_utils.js -> create_product_doc AND to Index in Elastic Search

### ISSUE THREAD

**Issue by morrisclay** [Zaubercraft/service_remote-data#1]
add images from result.json to product

`[{
...
  "images": [
    "https://mosaic01.ztat.net/vgs/media/pdp-thumb/JA/44/1G/00/FI/11/JA441G00F-I11@10.jpg",
    "https://mosaic02.ztat.net/vgs/media/pdp-thumb/JA/44/1G/00/FI/11/JA441G00F-I11@9.jpg",
    "https://mosaic01.ztat.net/vgs/media/pdp-thumb/JA/44/1G/00/FI/11/JA441G00F-I11@8.jpg",
    "https://mosaic02.ztat.net/vgs/media/pdp-thumb/JA/44/1G/00/FI/11/JA441G00F-I11@7.jpg",
    "https://mosaic01.ztat.net/vgs/media/pdp-thumb/JA/44/1G/00/FI/11/JA441G00F-I11@6.jpg",
    "https://mosaic02.ztat.net/vgs/media/pdp-thumb/JA/44/1G/00/FI/11/JA441G00F-I11@11.jpg"
  ],
...`

**Comment by mtambos** [comment]
implemented
