### ISSUE TITLE
don't take today as timestamp but use  | api.py -> def update()

### ISSUE THREAD

**Issue by morrisclay** [Zaubercraft/service_remote-data#2]
Apifier calls method:
```
POST /update
#payload:
{
_id: RUN-ID
}
```

please `GET https://api.apifier.com/v1/execs/**RUN-ID**` and take `startedAt` as reference date to construct the offer-index name (e.g: `offers-2016-12-01`) **not** `today`

Also refer to` [stats][pagesOutputted]` for the number of products in the json so you can iterate properly over the products in your code.

**Comment by mtambos** [comment]
implemented
